### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Ironheartcoder**
added div with class : span_tech_stack .
and a span tag with "tech stack"
in file "index-full"
nd also gave it some css properties to it

### CODE REVIEW

**Comment by harshgoel05** [comment]
Hey! Can do it in index.html,as all the contributors are doing it on index.html.

**Comment by Ironheartcoder** [comment]
> Hey! Can do it in index.html,as all the contributors are doing it on index.html.

ok sir :>

**Comment by Ironheartcoder** [comment]
chnges completed
 sry sir i sent same  files twice :P

let me know if u need any change

**Comment by harshgoel05** [comment]
Looks good to me! Thanks for contributing!

**Comment by harshgoel05** [comment]
Closing #9

**Pull request merged**
